name: NoodleDoodles
favicon: null
layout_spectrum: 0.56003
typography_spectrum: 0.35793
title: Noodle Doodles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12beff'
    - '#a8ed38'
    - '#000000'
    - '#364f0d'
    - '#6f9d23'
  brandStrength: 0.9653955777175725
  lightness: 0.31058374093845487
  saturation: 0.9759964398108423
  rhythmicContrast: 0
purpose: []
