name: NoodleDoodles
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35793
title: Noodle Doodles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12beff'
    - '#a8ed38'
    - '#000000'
    - '#364f0d'
    - '#6f9d23'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
